version: '3.5'

services:
  postgres-db:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ../datawarehouse/data:/var/lib/postgresql/data

  metabase-app:
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres # change
      MB_DB_DBNAME: postgres # change
      MB_DB_PORT: 5432 # change
      MB_DB_USER: postgres
      MB_DB_PASS: root
      MB_DB_HOST: postgres-db
    depends_on:
      - postgres-db
    links:
      - postgres-db

volumes:
  data:
  metabase-data: